export const BASE_URL = 'http://localhost/ktx/api/v1'
export const USERS_ENDPOINT = 'users'
export const LOAI_KHACHS_ENDPOINT = 'loaikhachs'
export const PHONGS_ENDPOINT = 'phongs'
export const KHACHS_ENDPOINT = 'khachluutrus'
